# Generated by Django 4.2 on 2023-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuser",
            name="subscription",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid")],
                default="free",
                max_length=10,
                verbose_name="Plans",
            ),
        ),
    ]
