# Generated by Django 4.2 on 2023-04-30 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_tuser_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
