# Generated by Django 4.2 on 2023-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_tuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tuser",
            name="phone_number_verified",
            field=models.BooleanField(default=False),
        ),
    ]
