# Generated by Django 4.2 on 2023-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_tuser_phone_number_tuser_phone_number_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuser",
            name="twilio_send_again_count",
            field=models.IntegerField(default=0),
        ),
    ]
