# Generated by Django 4.2 on 2023-05-10 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_tuser_twilio_send_again_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="email",
        ),
        migrations.AddField(
            model_name="contactus",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
