# Generated by Django 4.2 on 2023-04-11 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voice_record", models.FileField(upload_to="media/records")),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
    ]
