# Generated by Django 4.2 on 2023-04-11 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_record_voice_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="created",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
