# Generated by Django 4.2 on 2023-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_record_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
