# Generated by Django 4.2 on 2023-04-11 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_record_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("voice_recording", models.FileField(upload_to="recordings/")),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
        migrations.DeleteModel(
            name="Record",
        ),
    ]
