# Generated by Django 4.2 on 2023-04-12 06:34

from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_recording_session_alter_recording_voice_recording"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("session", models.IntegerField()),
                (
                    "transcription_file",
                    models.FileField(upload_to=main.models.recording_path),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Transcription",
                "verbose_name_plural": "Transcriptions",
            },
        ),
    ]
