# Generated by Django 4.2 on 2023-04-12 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_transcription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcription",
            old_name="transcription_file",
            new_name="file",
        ),
    ]
