# Generated by Django 4.2 on 2023-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_transcription_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="audio_type",
            field=models.CharField(default="opus", max_length=50),
            preserve_default=False,
        ),
    ]
