# Generated by Django 4.2 on 2023-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_recodringsession_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="session",
            field=models.CharField(max_length=100),
        ),
    ]
