# Generated by Django 4.2 on 2023-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_recording_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="session",
            field=models.CharField(max_length=100),
        ),
    ]
