# Generated by Django 4.2 on 2023-04-19 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_transcription_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="recodringsession",
            name="recordings",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="recodringsession",
            name="transcription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.transcription",
            ),
        ),
    ]
