# Generated by Django 4.2 on 2023-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_control_alter_recording_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="duration",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
