# Generated by Django 4.2 on 2023-05-01 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0022_rename_length_recording_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recording",
            name="language",
        ),
        migrations.AddField(
            model_name="transcription",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
