# Generated by Django 4.2 on 2023-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_recodringsession_user_alter_transcription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="transcription_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
